#!/bin/sh
sudo yum update -y
sudo yum install httpd -y
sudo service httpd start 
chkconfig httpd on 
cd /var/www/html
cat >> index.html << EOF
<html><body> this is first ec2 instance in az-a </body></html>
EOF
